@extends("layouts.home")
@section("title")
{{$setting->title}}
@endsection
@section("description")
{{$setting->description}}
@endsection
@section("keywords")
{{$setting->keywords}}
@endsection
@section("content")
@include('home._slider')
@include('home._grids')
@include('home._stats')
@include('home._populars')
@include('home._testimonals')
@endsection